controllerManager:
  kubeRbacProxy:
    image:
      repository: gcr.io/kubebuilder/kube-rbac-proxy
      tag: v0.5.0
  manager:
    image:
      repository: registry.k8s.io/capi-operator/cluster-api-operator
      tag: v0.1.0
    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 100Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP
