controllerManager:
  manager:
    image:
      repository: registry.k8s.io/capi-operator/cluster-api-operator
      tag: v0.9.0
    resources:
      limits:
        cpu: 100m
        memory: 150Mi
      requests:
        cpu: 100m
        memory: 100Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
webhookService:
  ports:
  - port: 443
    targetPort: 9443
  type: ClusterIP
