apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "capi-operator.fullname" . }}-manager-role
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  {{- include "capi-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "capi-operator.fullname" . }}-manager-rolebinding
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  {{- include "capi-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "capi-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: default
  namespace: '{{ .Release.Namespace }}'