apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "capi-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "capi-operator.fullname" . }}-serving-cert
  labels:
  {{- include "capi-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-addonprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vaddonprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - addonproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-bootstrapprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vbootstrapprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - bootstrapproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-controlplaneprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vcontrolplaneprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - controlplaneproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-coreprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vcoreprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - coreproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-infrastructureprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vinfrastructureprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - infrastructureproviders
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "capi-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-operator-cluster-x-k8s-io-v1alpha2-ipamprovider
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: vipamprovider.kb.io
  rules:
  - apiGroups:
    - operator.cluster.x-k8s.io
    apiVersions:
    - v1alpha2
    operations:
    - CREATE
    - UPDATE
    resources:
    - ipamproviders
  sideEffects: None