apiVersion: v1
kind: Service
metadata:
  name: {{ include "capi-operator.fullname" . }}-webhook-service
  labels:
    clusterctl.cluster.x-k8s.io/core: capi-operator
  {{- include "capi-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    clusterctl.cluster.x-k8s.io/core: capi-operator
    control-plane: controller-manager
  {{- include "capi-operator.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhookService.ports | toYaml | nindent 2 -}}